### ISSUE TITLE
Talk Proposal: HTTP/2 in Node.js? Sure, We can do that!

### ISSUE THREAD

**Issue by jasnell** [seattlejs/seattlejs#110]
# HTTP/2 in Node.js? Sure, We can do that!

Support for the HTTP/2 protocol has been added to Node.js. This talk will give a walk through of how it works, how to use it, and how to take advantage of the new features the protocol enables.

I am a core contributor to Node.js core and the primary author of the HTTP/2 implementation.

(available for meetups in 1Q or 2Q 2018)

* James M Snell
* [Twitter](https://twitter.com/jasnell)
* [Github](https://github.com/jasnell)

**Comment by ebrillhart** [comment]
Hi @jasnell! This would be an excellent talk - I'd imagine it would be a 25-30 minute feature?

Let me know if you'd be interested in speaking at any of the following Meetups:
February 8, 2018
March 8, 2018
April 12, 2018
May 10, 2018

If none of those work for you, we can look at later in Q2!

Also, I noticed that you're based in Fresno - just wanted to make sure you're aware that, due to being a community group, we don't have the budget to provide travel/lodging/etc. We'd love to have you if you can make it up to Seattle, though!

**Comment by jasnell** [comment]
Yes, a 25-30 minute feature would be best.

Let's target the Feb 8. I'll be able to handle my own travel/lodging. It will be a good opportunity to do some other business in the area :-)

**Comment by ebrillhart** [comment]
Great! Looking forward to it. If you "verbally" agree to our CoC (https://github.com/seattlejs/seattlejs/blob/master/code-of-conduct.md), I'll mark this as confirmed!

**Comment by jasnell** [comment]
Absolutely agree!

**Comment by nucleardreamer** [comment]
Sick!! Looking forward to this

**Comment by jasnell** [comment]
Hello @ebrillhart! Just want to confirm the Feb 8th meetup. Looking at the meetup detail page here (https://www.meetup.com/seattlejs/events/244673320/) it says that there are no confirmed speakers so wanted to make sure that we're still good to go for me to present on http2 that night!

**Comment by jefflembeck** [comment]
@jasnell confirmed! I'm updating now. Can I get a bio from you?
